- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check if user exists or not
    ansible.builtin.command: id roboshop
    ignore_errors: true
    register: user_output

  - name: print user output
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: create user
    ansible.builtin.command: useradd roboshop
    #when: user_output.rc != 0