- name: setup redis
  hosts: redis
  become: yes
  tasks:
  - name: disbale default nodejs
    ansible.builtin.command: dnf module disable redis -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: install nodejs
    ansible.builtin.package:
      name: redis
      state: installed

  - name: replace address
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes