- name: setup redis
  hosts: redis
  become: yes
  tasks:
  - name: disbale default nodejs
    ansible.builtin.command: dnf module disable redis -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable redis:7 -y