- name: setup user
  host: user
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: installed
  
  - name: add system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true
      comment: "roboshop system user"
  
  - name: delete app dir
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app dir
    ansible.builtin.file:
      path: /app
      state: present

  - name: Delete user.zip
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: Download user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  
  - name: unzip user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app

  - name: Install packages based on package.json.
    community.general.npm:
      path: /app

  - name: copy service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/

  - name: daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: start and enable service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
  
