- name: setup payment
  hosts: payment
  become: yes
  tasks:
  - name: install python packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - python3
    - gcc
    - python3-devel