- name: setup payment
  hosts: payment
  become: yes
  tasks:
  - name: install python packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - python3
    - gcc
    - python3-devel

  - name: add system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true
      comment: "roboshop system user"

  - name: delete app dir
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app dir
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete payment.zip
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: Download payment code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: unzip shipping
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: Install specified python requirements
    ansible.builtin.pip:
      requirements: /app/requirements.txt

  


  

  